### ISSUE TITLE
Quick add tasks cannot work at 1.4.0

### ISSUE THREAD

**Issue by FrankyYanFuzhang** [WayneGongCN/microsoft-todo-browser-ext#86]

**Comment by FrankyYanFuzhang** [comment]
1.2 version can quick add task, but at 1.4.0 can not

**Comment by WayneGongCN** [comment]
@FrankyYanFuzhang F sorry to trouble you

The quick add task function is deprecated in v1.4.0, see CHANGELOG and #71

In its place is the autofill feature #84

**Comment by FrankyYanFuzhang** [comment]
Got it.
Thanks for you reply!
________________________________
发件人: wayne ***@***.***>
发送时间: 2022年9月17日 15:55
收件人: WayneGongCN/microsoft-todo-browser-ext ***@***.***>
抄送: Fuzhang YAN ***@***.***>; Mention ***@***.***>
主题: [External]Re: [WayneGongCN/microsoft-todo-browser-ext] Quick add tasks cannot work at 1.4.0 (Issue #86)

你通常不会收到来自 ***@***.*** 的电子邮件。了解这一点为什么很重要<https://aka.ms/LearnAboutSenderIdentification>

[EXTERNAL] Do NOT click links or open attachments unless you recognize the sender and know the content is safe.

@FrankyYanFuzhang<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFrankyYanFuzhang&data=05%7C01%7Cfuzhangyan%40astri.org%7C90f504b1018d4957f96308da988203f9%7C585da53b260b448fb2ef9603ccf9e33e%7C1%7C0%7C637989981439892680%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=x%2BlkQqP%2Fwx9x%2Fa686LymZqcv5UQxzbLxh8q1LhKfpRc%3D&reserved=0> F sorry to trouble you

The quick add task function is deprecated in v1.4.0, see CHANGELOG and #71<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWayneGongCN%2Fmicrosoft-todo-browser-ext%2Fissues%2F71&data=05%7C01%7Cfuzhangyan%40astri.org%7C90f504b1018d4957f96308da988203f9%7C585da53b260b448fb2ef9603ccf9e33e%7C1%7C0%7C637989981439892680%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Dr1l1PdafsQLvZjPh5ivS2m1pXd%2Fv8JqafNy7KtlP9M%3D&reserved=0>

In its place is the autofill feature #84<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWayneGongCN%2Fmicrosoft-todo-browser-ext%2Fpull%2F84&data=05%7C01%7Cfuzhangyan%40astri.org%7C90f504b1018d4957f96308da988203f9%7C585da53b260b448fb2ef9603ccf9e33e%7C1%7C0%7C637989981439892680%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=k4KKfzy62OSo%2BvSQds5r8SKbvcegEfWmwPfOYbZz%2BV0%3D&reserved=0>

―
Reply to this email directly, view it on GitHub<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWayneGongCN%2Fmicrosoft-todo-browser-ext%2Fissues%2F86%23issuecomment-1250024033&data=05%7C01%7Cfuzhangyan%40astri.org%7C90f504b1018d4957f96308da988203f9%7C585da53b260b448fb2ef9603ccf9e33e%7C1%7C0%7C637989981439892680%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=A%2Bd8%2FRpm9Rd53chhKWLj%2BvFOQA8EmzhctqCCDgeKNIs%3D&reserved=0>, or unsubscribe<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA244M3SC7I6OVGFTMEDOMZLV6V2PVANCNFSM6AAAAAAQOB3WWY&data=05%7C01%7Cfuzhangyan%40astri.org%7C90f504b1018d4957f96308da988203f9%7C585da53b260b448fb2ef9603ccf9e33e%7C1%7C0%7C637989981439892680%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=psb083AYz1cVP9DChXoyXwBM9ugp%2FAPx%2FtDswuXX1wo%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

________________________________

CONFIDENTIALITY NOTICE:

The content of this email and any attachments (“Email”) is confidential, may be privileged, subject to copyright and may be read, copied and used only by the intended recipient.

If you are not the intended recipient, please notify the sender by return email or telephone immediately and erase all copies (including any attachments) and do not disclose the Email or any part of it to any person. Any use, retention, disclosure, copying, printing, forwarding or dissemination of the Email is strictly prohibited if you are not the intended recipient.

ASTRI reserve the right to monitor all email communications through ASTRI’s networks.

________________________________
